-- =============================================================
-- Migration 0006 — Fondations du module « Gestion de club »
-- =============================================================
-- À exécuter dans Supabase : Dashboard > SQL Editor > New query > Run.
-- Idempotent : ré-exécutable sans casse.
--
-- Pose le socle du portail de gestion (inscription, adhérents, paiements) :
--   - auth MULTI-RÔLES (bureau / enseignant / adhérent) via `profiles`,
--   - les 6 tables métier + leur RLS,
--   - un bucket Storage PRIVÉ pour les pièces (photos d'identité de mineurs).
--
-- MODÈLE DE SÉCURITÉ (résumé) :
--   - adhérent  : ne voit/écrit QUE sa propre famille (RLS scopée par auth.uid()).
--   - enseignant: lit les adhérents + met à jour les grades.
--   - bureau    : accès total (secrétariat / trésorier / admin).
--   - POINT CRITIQUE : seul le `bureau` peut écrire dans `paiements`
--     (encaissement). Un membre ne peut JAMAIS marquer son propre paiement
--     comme encaissé → la « règle d'or » des attestations reste inviolable.
--
-- ⚠️ RGPD : `adherents.photo_path` pointe vers le bucket PRIVÉ `dossiers`
-- (données de mineurs). Jamais de bucket public ici (≠ galerie).
-- =============================================================


-- =============================================================
-- 1) RÔLES : table `profiles`
-- =============================================================
-- Chaque utilisateur Auth a une ligne `profiles` (rôle). Un trigger crée
-- automatiquement la ligne (rôle 'adherent') à chaque inscription Auth.
-- (Les fonctions d'aide RLS et le trigger sont définis en section 2bis,
-- une fois que toutes les tables qu'ils référencent (dont `familles`)
-- existent — Postgres valide le corps des fonctions SQL à la création.)
create table if not exists public.profiles (
    user_id    uuid primary key references auth.users(id) on delete cascade,
    role       text not null default 'adherent' check (role in ('bureau', 'enseignant', 'adherent')),
    created_at timestamptz not null default now()
);


-- =============================================================
-- 2) TABLES MÉTIER
-- =============================================================
-- Montants TOUJOURS en CENTIMES (integer) : cohérent avec HelloAsso (phase 3)
-- et évite les erreurs d'arrondi des flottants. 210 € => 21000.

-- Config tarifaire, éditable par le bureau, une ligne par saison.
create table if not exists public.tarifs (
    saison            text primary key,
    cotisation_adulte integer not null default 21000,
    cotisation_enfant integer not null default 18000,
    cotisation_self   integer not null default 13000,
    tarif_bureau      integer not null default 3700,
    remise_passsport  integer not null default 5000,
    -- remises famille : { "2":1000, "3":3000, "4":5000, "5":7000 } (clé = nb d'inscrits, "5" = 5 et +).
    remises_famille   jsonb   not null default '{"2":1000,"3":3000,"4":5000,"5":7000}'::jsonb,
    actif             boolean not null default true,
    created_at        timestamptz not null default now()
);

-- Le foyer + le compte du référent (parent). 1 référent = 1 famille.
create table if not exists public.familles (
    id                bigint generated by default as identity primary key,
    referent_user_id  uuid not null unique references auth.users(id) on delete cascade,
    nom_referent      text not null default '',
    telephone_urgence text not null default '',
    adresse           text not null default '',
    code_postal       text not null default '',
    ville             text not null default '',
    created_at        timestamptz not null default now()
);

-- Une personne pratiquante, rattachée à une famille.
-- NB : `email` volontairement NON unique en base (des frères/sœurs peuvent
-- partager l'email d'un parent). L'unicité « FFK » est une règle métier
-- fédérale, pas une contrainte technique à imposer ici.
create table if not exists public.adherents (
    id                 bigint generated by default as identity primary key,
    famille_id         bigint not null references public.familles(id) on delete cascade,
    nom                text not null default '',
    prenom             text not null default '',
    date_naissance     date,
    genre              text check (genre in ('M', 'F')),
    email              text,
    cours_type         text check (cours_type in ('Adulte', 'Enfant', 'Self-Defense')),
    membre_bureau      boolean not null default false,
    passeport_sportif  boolean not null default false,
    numero_passeport   text not null default '',
    attestation_caf_ce boolean not null default false,
    droit_image        boolean not null default true,
    photo_path         text not null default '',
    grade_actuel       text not null default 'Ceinture Blanche',
    statut_dossier     text not null default 'Incomplet'
                            check (statut_dossier in ('Incomplet', 'Attente paiement', 'Validé')),
    created_at         timestamptz not null default now()
);

-- Le « panier » d'une inscription famille (la remise famille se calcule dessus).
create table if not exists public.dossiers (
    id            bigint generated by default as identity primary key,
    famille_id    bigint not null references public.familles(id) on delete cascade,
    saison        text not null default '',
    montant_total integer not null default 0,             -- centimes
    detail_calcul jsonb   not null default '{}'::jsonb,    -- traçabilité du calcul
    mode_paiement text not null default 'au_club' check (mode_paiement in ('au_club', 'en_ligne')),
    statut        text not null default 'attente_paiement'
                       check (statut in ('attente_paiement', 'paye_partiel', 'valide', 'annule')),
    created_at    timestamptz not null default now()
);

-- Les échéances de règlement (ex. 3 chèques). Écrit UNIQUEMENT par le bureau
-- au fur et à mesure des encaissements (cf. RLS). C'est ce qui conditionne
-- l'attestation : dossier réglé <=> toutes ses lignes `encaisse = true`.
create table if not exists public.paiements (
    id                bigint generated by default as identity primary key,
    dossier_id        bigint not null references public.dossiers(id) on delete cascade,
    montant           integer not null default 0,         -- centimes
    mode              text not null default 'cheque' check (mode in ('cheque', 'espece', 'cb', 'ancv', 'caf')),
    numero_cheque     text not null default '',
    encaisse          boolean not null default false,
    date_encaissement date,
    created_at        timestamptz not null default now()
);

-- Index sur les clés étrangères (jointures fréquentes côté bureau).
create index if not exists idx_familles_referent on public.familles(referent_user_id);
create index if not exists idx_adherents_famille on public.adherents(famille_id);
create index if not exists idx_dossiers_famille  on public.dossiers(famille_id);
create index if not exists idx_paiements_dossier on public.paiements(dossier_id);


-- =============================================================
-- 2bis) FONCTIONS D'AIDE RLS + TRIGGER
-- =============================================================
-- Définies ici (après les tables) car `my_famille_id()` référence
-- `public.familles`, qui doit déjà exister.
-- SECURITY DEFINER : elles lisent `profiles` en CONTOURNANT la RLS,
-- ce qui évite la récursion infinie (une policy sur profiles qui lirait profiles).
create or replace function public.is_bureau()
returns boolean language sql security definer stable set search_path = public as $$
    select exists (select 1 from public.profiles where user_id = auth.uid() and role = 'bureau');
$$;

-- Personnel encadrant = bureau OU enseignant.
create or replace function public.is_staff()
returns boolean language sql security definer stable set search_path = public as $$
    select exists (select 1 from public.profiles where user_id = auth.uid() and role in ('bureau', 'enseignant'));
$$;

-- Id de la famille dont l'utilisateur courant est le référent (une seule).
create or replace function public.my_famille_id()
returns bigint language sql security definer stable set search_path = public as $$
    select id from public.familles where referent_user_id = auth.uid() limit 1;
$$;

-- Trigger : crée le profil 'adherent' à la création d'un compte Auth.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    insert into public.profiles (user_id, role)
    values (new.id, 'adherent')
    on conflict (user_id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();


-- =============================================================
-- 3) ROW LEVEL SECURITY
-- =============================================================

-- --- profiles ---
alter table public.profiles enable row level security;

drop policy if exists "profiles_select" on public.profiles;
create policy "profiles_select" on public.profiles for select to authenticated
    using (user_id = auth.uid() or public.is_bureau());

-- Seul le bureau (re)définit les rôles : un membre ne peut pas se promouvoir.
drop policy if exists "profiles_update_bureau" on public.profiles;
create policy "profiles_update_bureau" on public.profiles for update to authenticated
    using (public.is_bureau()) with check (public.is_bureau());
-- (pas de policy INSERT/DELETE : l'insertion passe par le trigger SECURITY DEFINER.)

-- --- tarifs (lecture publique : ce sont des prix, pas un secret) ---
alter table public.tarifs enable row level security;

drop policy if exists "tarifs_select_public" on public.tarifs;
create policy "tarifs_select_public" on public.tarifs for select to anon, authenticated
    using (true);

drop policy if exists "tarifs_insert_bureau" on public.tarifs;
create policy "tarifs_insert_bureau" on public.tarifs for insert to authenticated
    with check (public.is_bureau());
drop policy if exists "tarifs_update_bureau" on public.tarifs;
create policy "tarifs_update_bureau" on public.tarifs for update to authenticated
    using (public.is_bureau()) with check (public.is_bureau());
drop policy if exists "tarifs_delete_bureau" on public.tarifs;
create policy "tarifs_delete_bureau" on public.tarifs for delete to authenticated
    using (public.is_bureau());

-- --- familles (le membre ne voit que la sienne) ---
alter table public.familles enable row level security;

drop policy if exists "familles_select" on public.familles;
create policy "familles_select" on public.familles for select to authenticated
    using (referent_user_id = auth.uid() or public.is_bureau());

drop policy if exists "familles_insert_self" on public.familles;
create policy "familles_insert_self" on public.familles for insert to authenticated
    with check (referent_user_id = auth.uid());

drop policy if exists "familles_update" on public.familles;
create policy "familles_update" on public.familles for update to authenticated
    using (referent_user_id = auth.uid() or public.is_bureau())
    with check (referent_user_id = auth.uid() or public.is_bureau());

drop policy if exists "familles_delete_bureau" on public.familles;
create policy "familles_delete_bureau" on public.familles for delete to authenticated
    using (public.is_bureau());

-- --- adherents (membre : sa famille ; enseignant : lecture + grade) ---
alter table public.adherents enable row level security;

drop policy if exists "adherents_select" on public.adherents;
create policy "adherents_select" on public.adherents for select to authenticated
    using (famille_id = public.my_famille_id() or public.is_staff());

drop policy if exists "adherents_insert_owner" on public.adherents;
create policy "adherents_insert_owner" on public.adherents for insert to authenticated
    with check (famille_id = public.my_famille_id() or public.is_bureau());

-- Mise à jour : le référent (avant validation) OU le personnel (dont l'enseignant
-- pour le grade). Le filtrage colonne par colonne n'existe pas en RLS : on
-- accepte l'update de ligne, l'UI restreint les champs proposés par rôle.
drop policy if exists "adherents_update" on public.adherents;
create policy "adherents_update" on public.adherents for update to authenticated
    using (famille_id = public.my_famille_id() or public.is_staff())
    with check (famille_id = public.my_famille_id() or public.is_staff());

drop policy if exists "adherents_delete" on public.adherents;
create policy "adherents_delete" on public.adherents for delete to authenticated
    using (famille_id = public.my_famille_id() or public.is_bureau());

-- --- dossiers ---
alter table public.dossiers enable row level security;

drop policy if exists "dossiers_select" on public.dossiers;
create policy "dossiers_select" on public.dossiers for select to authenticated
    using (famille_id = public.my_famille_id() or public.is_bureau());

drop policy if exists "dossiers_insert_owner" on public.dossiers;
create policy "dossiers_insert_owner" on public.dossiers for insert to authenticated
    with check (famille_id = public.my_famille_id() or public.is_bureau());

drop policy if exists "dossiers_update" on public.dossiers;
create policy "dossiers_update" on public.dossiers for update to authenticated
    using (famille_id = public.my_famille_id() or public.is_bureau())
    with check (famille_id = public.my_famille_id() or public.is_bureau());

drop policy if exists "dossiers_delete_bureau" on public.dossiers;
create policy "dossiers_delete_bureau" on public.dossiers for delete to authenticated
    using (public.is_bureau());

-- --- paiements : LECTURE membre, mais ÉCRITURE bureau UNIQUEMENT ---
-- (c'est le verrou de la règle d'or : le membre ne peut pas s'auto-encaisser).
alter table public.paiements enable row level security;

drop policy if exists "paiements_select" on public.paiements;
create policy "paiements_select" on public.paiements for select to authenticated
    using (
        public.is_bureau()
        or dossier_id in (select id from public.dossiers where famille_id = public.my_famille_id())
    );

drop policy if exists "paiements_insert_bureau" on public.paiements;
create policy "paiements_insert_bureau" on public.paiements for insert to authenticated
    with check (public.is_bureau());
drop policy if exists "paiements_update_bureau" on public.paiements;
create policy "paiements_update_bureau" on public.paiements for update to authenticated
    using (public.is_bureau()) with check (public.is_bureau());
drop policy if exists "paiements_delete_bureau" on public.paiements;
create policy "paiements_delete_bureau" on public.paiements for delete to authenticated
    using (public.is_bureau());


-- =============================================================
-- 4) STORAGE — bucket PRIVÉ `dossiers` (photos d'identité, etc.)
-- =============================================================
-- Convention de chemin : `<auth.uid()>/<fichier>` → un membre n'accède qu'à
-- ses propres fichiers ; le bureau accède à tout.
-- NB : si le SQL Editor refuse ces policies (droits), les créer via
-- Dashboard > Storage > Policies (mêmes conditions).
insert into storage.buckets (id, name, public)
values ('dossiers', 'dossiers', false)
on conflict (id) do nothing;

drop policy if exists "dossiers_obj_insert_own" on storage.objects;
create policy "dossiers_obj_insert_own" on storage.objects for insert to authenticated
    with check (
        bucket_id = 'dossiers'
        and (storage.foldername(name))[1] = auth.uid()::text
    );

drop policy if exists "dossiers_obj_select_own_or_bureau" on storage.objects;
create policy "dossiers_obj_select_own_or_bureau" on storage.objects for select to authenticated
    using (
        bucket_id = 'dossiers'
        and ((storage.foldername(name))[1] = auth.uid()::text or public.is_bureau())
    );

drop policy if exists "dossiers_obj_delete_own_or_bureau" on storage.objects;
create policy "dossiers_obj_delete_own_or_bureau" on storage.objects for delete to authenticated
    using (
        bucket_id = 'dossiers'
        and ((storage.foldername(name))[1] = auth.uid()::text or public.is_bureau())
    );


-- =============================================================
-- 5) DONNÉES INITIALES
-- =============================================================
-- 5a) Tarifs de la saison en cours (valeurs du dossier papier 2022/2023,
--     ajustables ensuite par le bureau). Pass'Sport 50 € (change chaque année).
insert into public.tarifs (saison) values ('2026-2027')
on conflict (saison) do nothing;

-- 5b) Backfill : tous les comptes Auth existants reçoivent un profil 'adherent'…
insert into public.profiles (user_id, role)
select id, 'adherent' from auth.users
on conflict (user_id) do nothing;

-- 5c) …puis on promeut le compte admin historique en 'bureau'.
-- ⚠️ Adapter l'email si le compte bureau principal est différent.
update public.profiles
set role = 'bureau'
where user_id in (select id from auth.users where email = 'marsella.lorenzo@gmail.com');
