-- =============================================================
-- Migration 0009 — Factures (documents fiscaux numérotés)
-- =============================================================
-- À exécuter dans Supabase : Dashboard > SQL Editor > New query > Run.
-- Idempotent (IF NOT EXISTS / CREATE OR REPLACE / drop policy if exists).
--
-- POURQUOI une table + une fonction (et pas une simple génération PDF) :
-- en droit français, une facture est une pièce comptable qui doit porter un
-- NUMÉRO unique issu d'une séquence chronologique CONTINUE, être émise par
-- l'association (jamais auto-émise par l'adhérent) et rester IMMUABLE.
--   → la numérotation se fait donc en base, de façon ATOMIQUE et réservée au
--     `bureau`, via la fonction `emettre_facture()` (SECURITY DEFINER).
--   → le navigateur ne fait que rendre le PDF à partir de la ligne renvoyée.
--
-- L'« attestation de paiement » (espace adhérent) est un document distinct,
-- NON fiscal : pas de numéro, générée côté client en lecture seule. Elle ne
-- passe donc PAS par cette table.
-- =============================================================


-- =============================================================
-- 1) SÉQUENCE de numérotation (continuité chronologique)
-- =============================================================
-- Une seule séquence monotone pour tout le club : garantit l'absence de
-- doublon et l'ordre d'émission. Le numéro affiché préfixe l'année d'émission
-- (ex. « 2026-0001 »), purement cosmétique ; la continuité vient de la séquence.
create sequence if not exists public.factures_numero_seq;


-- =============================================================
-- 2) TABLE `factures`
-- =============================================================
-- `dossier_id` UNIQUE : une seule facture par dossier (ré-émission = même
-- numéro, cf. `emettre_facture`). `snapshot` fige les données au moment de
-- l'émission (immuabilité : la facture ne doit pas « bouger » si la famille
-- ou les tarifs changent ensuite). Montant en CENTIMES (cohérent partout).
create table if not exists public.factures (
    id          bigint generated by default as identity primary key,
    numero      text    not null unique,
    dossier_id  bigint  not null unique references public.dossiers(id) on delete restrict,
    famille_id  bigint  not null references public.familles(id) on delete restrict,
    saison      text    not null default '',
    montant     integer not null default 0,             -- centimes (TTC)
    snapshot    jsonb   not null default '{}'::jsonb,    -- copie figée (immuabilité légale)
    emise_par   uuid    references auth.users(id),       -- membre du bureau émetteur
    emise_le    timestamptz not null default now()
);

create index if not exists idx_factures_famille on public.factures(famille_id);


-- =============================================================
-- 3) ROW LEVEL SECURITY
-- =============================================================
-- Lecture : le bureau (tout) + la famille concernée (sa propre facture).
-- Écriture : AUCUNE policy → bloquée pour tout client. La seule voie d'écriture
-- est la fonction `emettre_facture` (SECURITY DEFINER, propriétaire postgres),
-- qui contourne la RLS après avoir vérifié le rôle `bureau`. Verrou « émission
-- réservée au bureau » identique à celui des `paiements`.
alter table public.factures enable row level security;

drop policy if exists "factures_select" on public.factures;
create policy "factures_select" on public.factures for select to authenticated
    using (famille_id = public.my_famille_id() or public.is_bureau());


-- =============================================================
-- 4) FONCTION D'ÉMISSION (atomique, bureau uniquement)
-- =============================================================
-- Contrat :
--   - réservé au `bureau` (sinon exception) → respect de la législation ;
--   - refuse si le dossier n'est PAS soldé (statut 'valide' OU somme encaissée
--     >= montant_total) → on ne facture jamais un règlement incomplet ;
--   - IDEMPOTENTE : si une facture existe déjà pour le dossier, on la renvoie
--     telle quelle (même numéro) → pas de doublon de numérotation ;
--   - fige un `snapshot` (référent + adresse + adhérents + détail du calcul).
create or replace function public.emettre_facture(p_dossier_id bigint)
returns public.factures
language plpgsql
security definer
set search_path = public
as $$
declare
    v_dossier  public.dossiers;
    v_famille  public.familles;
    v_paye     integer;
    v_facture  public.factures;
    v_numero   text;
    v_snapshot jsonb;
begin
    -- 1) Garde de rôle : seul le bureau émet une facture.
    if not public.is_bureau() then
        raise exception 'Émission réservée au bureau.' using errcode = '42501';
    end if;

    -- 2) Dossier + famille.
    select * into v_dossier from public.dossiers where id = p_dossier_id;
    if not found then
        raise exception 'Dossier introuvable (%).', p_dossier_id;
    end if;
    select * into v_famille from public.familles where id = v_dossier.famille_id;

    -- 3) Idempotence : une facture déjà émise est renvoyée telle quelle.
    select * into v_facture from public.factures where dossier_id = p_dossier_id;
    if found then
        return v_facture;
    end if;

    -- 4) Le dossier doit être soldé.
    select coalesce(sum(montant) filter (where encaisse), 0) into v_paye
    from public.paiements where dossier_id = p_dossier_id;
    if v_dossier.statut <> 'valide' and v_paye < v_dossier.montant_total then
        raise exception 'Dossier non soldé : facture impossible tant que le règlement est incomplet.'
            using errcode = 'P0001';
    end if;

    -- 5) Numéro atomique (nextval) + snapshot figé.
    v_numero := to_char(now(), 'YYYY') || '-' || lpad(nextval('public.factures_numero_seq')::text, 4, '0');

    v_snapshot := jsonb_build_object(
        'referent',    v_famille.nom_referent,
        'adresse',     v_famille.adresse,
        'code_postal', v_famille.code_postal,
        'ville',       v_famille.ville,
        'detail',      v_dossier.detail_calcul,
        'adherents',   coalesce((
            select jsonb_agg(jsonb_build_object('nom', a.nom, 'prenom', a.prenom, 'cours', a.cours_type)
                             order by a.id)
            from public.adherents a where a.famille_id = v_dossier.famille_id
        ), '[]'::jsonb)
    );

    insert into public.factures (numero, dossier_id, famille_id, saison, montant, snapshot, emise_par)
    values (v_numero, p_dossier_id, v_dossier.famille_id, v_dossier.saison,
            v_dossier.montant_total, v_snapshot, auth.uid())
    returning * into v_facture;

    return v_facture;
end;
$$;

-- La fonction est appelable par tout compte connecté ; la garde `is_bureau()`
-- à l'intérieur fait le tri (un adhérent reçoit l'exception 42501).
grant execute on function public.emettre_facture(bigint) to authenticated;
