-- =============================================================
-- Migration 0016 — Refonte : saisons (historique) + cours (par saison)
-- =============================================================
-- À exécuter dans Supabase : Dashboard > SQL Editor > New query > Run.
-- Idempotent : ré-exécutable sans casse (IF NOT EXISTS / ON CONFLICT / NOT EXISTS).
--
-- POURQUOI : la table `saison` (0005, document JSONB singleton id=1) ne gérait
-- qu'UNE saison à la fois et n'avait pas de vraie notion de « cours ». On passe
-- à un modèle RELATIONNEL :
--   - `saisons` : une ligne par saison (HISTORIQUE conservé), un flag `active`
--     (au plus une seule active à la fois), + les libellés/notes/tarif licence
--     et le `nb_licencies` affiché publiquement (page club).
--   - `cours`   : une ligne par cours d'une saison (FK saison_id). Porte le
--     `cours_type` (lien avec adherents.cours_type), le professeur, la capacité
--     max, les horaires (jours/heures/lieu) et le tarif (cours seul, centimes).
--
-- ÉDITION : déplacée du « mode admin unique » d'index.html vers l'Espace Bureau
-- (RLS bureau, comme la table `tarifs`). Lecture publique (anon) pour l'affichage
-- sur l'accueil et la page club.
--
-- ⚠️ Montants TOUJOURS en CENTIMES (integer), cohérent avec le reste du module.
-- L'ancienne table `saison` (0005) est laissée en place (trace), mais n'est plus
-- lue par le site après cette migration.
-- =============================================================


-- =============================================================
-- 1) TABLE `saisons` (historique multi-saisons)
-- =============================================================
create table if not exists public.saisons (
    id            bigint generated by default as identity primary key,
    label         text not null unique,                 -- ex : '2026-2027' (sert aussi de clé pour dossiers.saison)
    date_debut    date,
    date_fin      date,
    active        boolean not null default false,
    tarif_licence integer not null default 3700,        -- licence FFK (centimes), ajoutée par adhérent
    nb_licencies  integer not null default 0,           -- saisi par le bureau, affiché sur club.html
    tarifs_note   text not null default '',             -- note « remises familles »
    licence_note  text not null default '',             -- note « licence FFK »
    notes         text not null default '',
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now()
);

-- Au plus UNE saison active à la fois : index partiel unique sur active = true.
-- (Une activation côté UI doit donc d'abord désactiver l'ancienne active.)
create unique index if not exists uniq_saison_active
    on public.saisons (active) where active;


-- =============================================================
-- 2) TABLE `cours` (cours d'une saison)
-- =============================================================
create table if not exists public.cours (
    id           bigint generated by default as identity primary key,
    saison_id    bigint not null references public.saisons(id) on delete cascade,
    -- Lien avec adherents.cours_type (même vocabulaire). NULL = ligne d'affichage
    -- seule (pas rattachée au calcul d'inscription).
    cours_type   text check (cours_type in ('Baby', 'Enfant', 'Adulte', 'Self-Defense')),
    libelle      text not null default '',
    professeur   text not null default '',
    capacite_max integer,                                -- NULL = illimité
    jours        text not null default '',
    heures       text not null default '',
    lieu         text not null default '',
    accent       text not null default 'dojo' check (accent in ('dojo', 'corail')),
    prix         integer not null default 0,             -- cours seul, HORS licence (centimes)
    position     integer not null default 0,             -- ordre d'affichage
    created_at   timestamptz not null default now()
);

create index if not exists idx_cours_saison on public.cours(saison_id);


-- =============================================================
-- 3) ROW LEVEL SECURITY (lecture publique, écriture bureau)
-- =============================================================
-- Mêmes règles que la table `tarifs` (0006) : ce sont des horaires/prix publics,
-- mais seul le bureau les édite. `is_bureau()` est défini par la migration 0006.
alter table public.saisons enable row level security;
alter table public.cours   enable row level security;

-- --- saisons ---
drop policy if exists "saisons_select_public" on public.saisons;
create policy "saisons_select_public" on public.saisons for select to anon, authenticated
    using (true);

drop policy if exists "saisons_insert_bureau" on public.saisons;
create policy "saisons_insert_bureau" on public.saisons for insert to authenticated
    with check (public.is_bureau());
drop policy if exists "saisons_update_bureau" on public.saisons;
create policy "saisons_update_bureau" on public.saisons for update to authenticated
    using (public.is_bureau()) with check (public.is_bureau());
drop policy if exists "saisons_delete_bureau" on public.saisons;
create policy "saisons_delete_bureau" on public.saisons for delete to authenticated
    using (public.is_bureau());

-- --- cours ---
drop policy if exists "cours_select_public" on public.cours;
create policy "cours_select_public" on public.cours for select to anon, authenticated
    using (true);

drop policy if exists "cours_insert_bureau" on public.cours;
create policy "cours_insert_bureau" on public.cours for insert to authenticated
    with check (public.is_bureau());
drop policy if exists "cours_update_bureau" on public.cours;
create policy "cours_update_bureau" on public.cours for update to authenticated
    using (public.is_bureau()) with check (public.is_bureau());
drop policy if exists "cours_delete_bureau" on public.cours;
create policy "cours_delete_bureau" on public.cours for delete to authenticated
    using (public.is_bureau());


-- =============================================================
-- 4) REPRISE DES DONNÉES (saison 2026-2027 actuelle)
-- =============================================================
-- Reprend le contenu de l'ancienne saison JSONB (horaires + tarifs fusionnés
-- dans le modèle `cours`). nb_licencies repris de l'affichage historique (105).
insert into public.saisons (label, date_debut, date_fin, active, tarif_licence, nb_licencies, tarifs_note, licence_note)
values (
    '2026-2027', '2026-09-01', '2027-06-30', true, 3700, 105,
    'Des remises familles sont appliquées (de -10€ à -70€ selon le nombre d''inscrits).',
    '* Prévoir 37€ supplémentaires pour la licence FFK.'
)
on conflict (label) do nothing;

-- Cours de la saison 2026-2027 (n'insère que si la saison n'a pas déjà de cours).
insert into public.cours (saison_id, cours_type, libelle, jours, heures, lieu, accent, prix, position)
select s.id, v.cours_type, v.libelle, v.jours, v.heures, v.lieu, v.accent, v.prix, v.position
from public.saisons s
cross join (values
    ('Baby',         'Baby Karaté',           'Mardi et Jeudi',    '18h30 - 19h30', 'Gymnase Auguste Delaune', 'dojo',   18300, 0),
    ('Enfant',       'Enfants',               'Lundi et Vendredi', '18h00 - 19h00', 'École Louise Michel',     'dojo',   20300, 1),
    ('Adulte',       'Ados / Adultes',        'Mardi et Jeudi',    '19h30 - 21h00', 'Gymnase Auguste Delaune', 'dojo',   23300, 2),
    ('Self-Defense', 'Self-Défense Féminine', 'Dimanche',          '11h00 - 12h30', 'Gymnase Auguste Delaune', 'corail', 13300, 3)
) as v(cours_type, libelle, jours, heures, lieu, accent, prix, position)
where s.label = '2026-2027'
  and not exists (select 1 from public.cours c where c.saison_id = s.id);
